
name: 部署StockSheetWeb

on:
    push:
        branches:
            # 確保這是你正在使用的分支名稱
            - main
    # 手動觸發部署
#    workflow_dispatch:

# 增加寫入權限
#permissions:
#    contents: write

jobs:
    deploy-gh-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  # “最近更新時間” 等 git 日誌相關資訊，需要拉取全部提交記錄
                  fetch-depth: 0
                  # 如果你文檔需要 Git 子模組，取消註釋下一行
                  # submodules: true

            - name: 安裝 pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8.6.2
                  # 使用 pnpm 安裝依賴
                  run_install: true


            - name: 設置 Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  # 快取 pnpm 依賴
                  cache: pnpm


            # 運行建構指令碼
            - name: Build VuePress site
              run: pnpm docs:build

#            # 查看 workflow 的檔案來獲取更多資訊
#            # @see https://github.com/crazy-max/ghaction-github-pages
            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  # 部署到 gh-pages 分支
                  target_branch: main
                  repo: 94lanyu/94lanyu.github.io
                  # 部署目錄為 VuePress 的默認輸出目錄
                  build_dir: src/.vuepress/dist
              env:
                  # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            # 2、部署到 GitHub Pages
#            - name: Deploy to GitHub Pages
#              uses: JamesIves/github-pages-deploy-action@releases/v3
#              with:
#                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#                  REPOSITORY_NAME: StockSheet/lazypisces.github.io
#                  BRANCH: master
#                  FOLDER: src/.vuepress/dist
#                  #注意這裡的 public 是倉庫根目錄下的 public，也就是 npm run build 生成靜態資源的路徑，比如有的人是 `docs/.vuepress/dist`